version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:558443770462:task-definition/django-task:5"
        LoadBalancerInfo:
          ContainerName: "django"
          ContainerPort: 8081
